### ISSUE TITLE
server is not getting started

### ISSUE THREAD

**Issue by Boby900** [bobangajicsm/react-weather-app#3]
@bobangajicsm 
# react-scripts is not recognized
#### also added the scipts in the package.json file, but still not working.
#2 
![Screenshot (11)](https://user-images.githubusercontent.com/111265239/208698139-3e5a7996-4858-4f7f-9e38-a7b2b0be703f.png)

**Comment by omkarchillal** [comment]
thats because you didnt replace your api keys. 
make changes in api.js file by replacing the API keys which you can get from rapid API and open weather

**Comment by Boby900** [comment]
thanks I got this
