### ISSUE TITLE
search bar issue

### ISSUE THREAD

**Issue by ekaansh276** [bobangajicsm/react-weather-app#6]
i followed the yt tutorial completely, but when i enter my city name in search bar, its showing nothing but keeps fluctuating between no results & searching phases. what do i need to check in my code?

**Comment by cubinCheese** [comment]
I think I had the same issue where the search results would cycle between "no options" and "loading". And the console would display these GET requests:
`search.js:14 GET https://wft-geo-db.p.rapidapi.com/v1/geo/adminDivisions/cities?minPopulation=1000000&namePrefix= 429 (Too Many Requests)` 

and 

`(search.js:14) GET https://wft-geo-db.p.rapidapi.com/v1/geo/adminDivisions/cities?minPopulation=1000000&namePrefix= 404 (Not Found)`.

I fixed it by changing the GEO_API_URL endpoint. 
So, from
![image](https://github.com/bobangajicsm/react-weather-app/assets/93562548/da20b72e-1c73-4795-b1a2-2a080602e8b9)
to: 
![image](https://github.com/bobangajicsm/react-weather-app/assets/93562548/982bdc33-f497-432d-85b8-92368e0a022f).
